version: '3.7'
services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "7000:7000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - "8000:8000"
    depends_on:
      - model-index
    volumes:
      - ./backend/:/backend


  model-index:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - node.name=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./es-data:/usr/share/elasticsearch/data